### PR TITLE
add conversion script and functions from cobidas checklist

### LINKED ISSUE #3: conversion tools
hey @satra 

in case some of the ugly python code I have been creating to create the cobidas schema is useful, feel free to reuse it to recycle and improve.

it is here: https://github.com/Remi-Gau/COBIDAS_chckls/tree/master/conversion_scripts

### PR DESCRIPTION
**Pull request by Remi-Gau**
Should fix #3 

@satra 

Transferring here the few scripts and functions used to convert spreadsheets into schema.

The script is based on COBIDAS so it assumes that one spreadsheet describes a whole protocol and will almost always contain several activities that will need to be created and added to the protocol.

I started adding some modularity to deal with functions for items, activities and protocol separately but I suspect that those could be turned into classes as well: but coming from the matlab school I still think with function and procedural rather than object and classes + methods. Baby steps.

Also those scripts are 2 weeks old so they output things that are not up to date with the latest shape of the schema.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@satra 

Finally took the time to try doing some actual object oriented programming and creating my first classes in python to make some tools that could be useful to create new protocols, activity, items...

The general idea is that the classes for protocol, activity and schema are all based on a schema class because I quickly realized there was a lot of overlap.

There is room for improvement and some things are not "general" enough and too centered on my specific needs. 

Also I have created some methods to set some "default" content in the jsonld: not sure if this is something we want to do.

Similarly the actual URI and schema version, I use to point to all the definitions are "hard coded" in the schema class: not sure if we want to make that more flexible.

Will try to keep working on it but if you have suggestions, pointers... I am listening.

The scripts that I use and that rely on those classes are on a separate PR on the builder repo: in case it is unclear how those are used.
https://github.com/ReproNim/reproschema-builder/pull/6

**Comment by satra** [comment]
thanks @Remi-Gau - i'll merge this in for now, but we may want to do something a little more complex :) for example building the python classes (using say pydantic or attrs) directly from the schema/shape file.

unless those words were completely clear i can take a stab sometime soon at at least a process. this would allow us to just maintain the schema rather than both code and schema changes. although in the short run what you have done is a great starting point.

**Comment by Remi-Gau** [comment]
If there are ways to automate that (am now googling those said words) let's go for it. 

For me this was also a way to train my baby pythonic muscles. :-)

**Comment by satra** [comment]
closing to move to #10

**Pull request closed without merging**
