### PR TITLE
remove 3.7, add 3.11 & 3.12

### PR DESCRIPTION
**Pull request by yibeichan**
python 3.7 kept failing GA with the following error:
```
Run actions/setup-python@v2
  with:
    python-version: [3](https://github.com/ReproNim/reproschema-py/actions/runs/8881434819/job/24383768417#step:3:3).7
    token: ***
Version 3.7 was not found in the local cache
Error: Version 3.7 with arch arm6[4](https://github.com/ReproNim/reproschema-py/actions/runs/8881434819/job/24383768417#step:3:4) not found
```
I guess it's time to say goodbye

### CODE REVIEW

**Comment by satra** [comment]
add 3.12 as well

**Comment by yibeichan** [comment]
okay great, 3.11 was okay but 3.12 failed. it seems that we need to fix something

**Comment by Remi-Gau** [comment]
error seems related to this (versioneer related)

https://github.com/pydata/pandas-datareader/issues/969

My 2 cents: stick to 3.11 in this PR, modernize the packaging (pyproject.toml + build with hatchling-vcs to drop versionner) and support 3.12

**Comment by Remi-Gau** [comment]
>  modernize the packaging (pyproject.toml + build with hatchling-vcs to drop versionner) 

I can take care of this

**Comment by yibeichan** [comment]
> > modernize the packaging (pyproject.toml + build with hatchling-vcs to drop versionner)
> 
> I can take care of this

sounds good! removed 3.12. I don't even know what "hatchling-vcs to drop versionner" means

**Comment by satra** [comment]
perhaps just follow the versioneer steps in their readme. i think that should work to update versioneer quite easily. also may need to update version of auto in the github workflows.

**Comment by yibeichan** [comment]
yay, updated versioneer works. i'm going to merge this one

**Pull request merged**
