### PR TITLE
add audio and video to FieldShape

### PR DESCRIPTION
**Pull request by sanuann**

### CODE REVIEW

**Comment by satra** [comment]
please send this to the reproschema repo - this gets updated from there.

**Comment by sanuann** [comment]
> please send this to the reproschema repo - this gets updated from there.

so I need not update here? I thought I needed to both places..

**Comment by satra** [comment]
we need it here too, but i generate this from the other one, where we verify everyhting is in place and release a new version of the schema.

**Comment by sanuann** [comment]
done

**Comment by sanuann** [comment]
@satra please merge.

**Comment by sanuann** [comment]
@satra I've updated the changes here too. Please merge.

**Pull request merged**
