### PR TITLE
fix isVis based on Field annotation

### PR DESCRIPTION
**Pull request by yibeichan**
1. if "@READONLY" is in `Field annotation`, set `isVis: False`
2. if "@CALCTEXT` is  in `Field annotation`, set `isVis: False`, we also update compute list
3. also changed `csv.Reader `to `pandas`
4. added some tests, passed

TODO:
we may want to update the following  (line 305) as well, I need more time to figure out the logic here
```
elif field_type in COMPUTE_LIST:
    rowData["ui"]["readonlyValue"] = True
```

### CODE REVIEW

**Comment by yibeichan** [comment]
@satra do you remember what this `readonlyValue` in UI is for? 
Currently, if an item is purely based on calculation, we put it True for `readonlyValue`. 
Here we made `isVis` false for items have `@readonly` in redcap `Field Annotation` (like  “session_id”, “started_at”,  “completed_at”,  “duration”). I'm thinking whether we want to set `rowData["ui"]["readonlyValue"] = True` for them as well
https://github.com/ReproNim/reproschema-py/blob/c6aa6877c594809f61383707025d36da24ffd2d1/reproschema/redcap2reproschema.py#L326

**Comment by satra** [comment]
i think it was in the schema to allow showing computed values but not having them be changed (so `isVis=True` and `readOnly=True`. whether the computed value should be showed from redcap could be left to a user later to change. i don't know if there is a field in the redcap table or a similar option in redcap. i think your current approach is fine for `@readonly` options in redcap.

**Comment by satra** [comment]
and set `readOnly` to `True` for them.

**Comment by yibeichan** [comment]
for computed values, `isVis` will be the computing logic, not exactly `True`.
for `@READONLY` from redcap, we will have `isVis` as `False` but `readOnly=True` in `ui`
sounds good? if yes, then you can merge it

**Pull request merged**
